### ISSUE TITLE
Deployment broken

### ISSUE THREAD

**Issue by michael-markl** [elite-se/elite-se.study-planner#46]
It seems the deployment on heroku is broken. Is there a way to restore the deployment easily ? :D

**Comment by FabianWildgrube** [comment]
Oh, thanks for noticing! Heroku has cancelled their free containers one of which was the StudyPlanner 😥
I haven't looked into a free alternative. Statically hosting would always be an option, which is something I can do on my private server. But that doesn't really provide a seamless CI/CD that Heroku had. Happy for any ideas (and PRs 😉) to switch to a different provider.

**Comment by FabianWildgrube** [comment]
There's two new deployments now 😆 
 I found [render.com](https://render.com/) which seems like a really nice tool and it offers a free tier. Setting up the deployment took me literally two minutes and they say they support automatic deployments for PRs 🤩 .
The new deployment can be found here: https://elite-se-study-planner.onrender.com/

Daniel Albert (@esclear) was so kind to host the site statically on his own server as well: https://mathe.sexy/se-planner/

I will add both links to the Readme and document the new deployment on render.com
