### ISSUE TITLE
70 ECTS in Fachlicher Lehre nicht geprüft

### ISSUE THREAD

**Issue by ckaarle** [elite-se/elite-se.study-planner#5]
Laut §19.4 (PO) müssen 70 ECTS aus dem Bereich Fachliche Lehre (also Pflicht-, Wahlveranstaltungen, Seminare, ...) kommen. Momentan ist es möglich, bei < 120 ECTS mit zusätzlichen Softskill-Einheiten aufzufüllen, die sind aber laut PO eigentlich auf 10 ECTS begrenzt.

**Comment by FabianWildgrube** [comment]
Danke für den Hinweis, das hatte ich übersehen. Werde ich nach den Prüfungen drum kümmern.
